package com.black_survivor.black_survivor_dictinary

import android.os.Bundle
import android.widget.ImageView
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.GridLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.google.android.gms.ads.AdRequest
import com.google.android.gms.ads.AdView
import com.google.android.gms.ads.MobileAds

var abc:Int = -1
class map_explan : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_map_explan)

        MobileAds.initialize(this,"ca-app-pub-8417791108068506~7524991405")

        var gotcha = findViewById<TextView>(R.id.gotcha)
        var creature = findViewById<TextView>(R.id.creature)
        var rvmap = findViewById<RecyclerView>(R.id.rv_mapitem)
        var map_image = findViewById<ImageView>(R.id.map_image)
        var animal1 = findViewById<ImageView>(R.id.animal1)
        var animal2 = findViewById<ImageView>(R.id.animal2)
        var animal3 = findViewById<ImageView>(R.id.animal3)
        var text1 = findViewById<TextView>(R.id.ani_tex1)
        var text2 = findViewById<TextView>(R.id.ani_tex2)
        var text3 = findViewById<TextView>(R.id.ani_tex3)
        var title = findViewById<TextView>(R.id.map_title)

        var adview = findViewById<AdView>(R.id.adView1)
        val adRequest = AdRequest.Builder().build()
        adview.loadAd(adRequest)

        if(intent.hasExtra("0"))
            abc = 0
        if(intent.hasExtra("1"))
            abc = 1
        if(intent.hasExtra("2"))
            abc = 2
        if(intent.hasExtra("3"))
            abc = 3
        if(intent.hasExtra("4"))
            abc = 4
        if(intent.hasExtra("5"))
            abc = 5
        if(intent.hasExtra("6"))
            abc = 6
        if(intent.hasExtra("7"))
            abc = 7
        if(intent.hasExtra("8"))
            abc = 8
        if(intent.hasExtra("9"))
            abc = 9
        if(intent.hasExtra("10"))
            abc = 10
        if(intent.hasExtra("11"))
            abc = 11
        if(intent.hasExtra("12"))
            abc = 12
        if(intent.hasExtra("13"))
            abc = 13
        if(intent.hasExtra("14"))
            abc = 14
        if(intent.hasExtra("15"))
            abc = 15
        if(intent.hasExtra("16"))
            abc = 16
        //뷰에 텍스트뷰 하나 생성. gone으로 , 초기값0 인텐트받거나 리스트 누를시 값변경으로 이벤트 발생시키기

        var map_Item = arrayListOf(
            Map_Item.map_Itemlist(R.drawable.head_hairband ,"머리띠")
        )

        when(abc){
            0 -> map_image.setImageResource(R.drawable.picture00)
            1 -> map_image.setImageResource(R.drawable.picture01)
            2 -> map_image.setImageResource(R.drawable.picture02)
            3 -> map_image.setImageResource(R.drawable.picture03)
            4 -> map_image.setImageResource(R.drawable.picture04)
            5 -> map_image.setImageResource(R.drawable.picture05)
            6 -> map_image.setImageResource(R.drawable.picture06)
            7 -> map_image.setImageResource(R.drawable.picture07)
            8 -> map_image.setImageResource(R.drawable.picture08)
            9 -> map_image.setImageResource(R.drawable.picture09)
            10 -> map_image.setImageResource(R.drawable.picture10)
            11 -> map_image.setImageResource(R.drawable.picture11)
            12 -> map_image.setImageResource(R.drawable.picture12)
            13 -> map_image.setImageResource(R.drawable.picture13)
            14 -> map_image.setImageResource(R.drawable.picture14)
            15 -> map_image.setImageResource(R.drawable.picture15)
        }


        rvmap.layoutManager = GridLayoutManager(this, 2).also { it.orientation = GridLayoutManager.HORIZONTAL }
        rvmap.setHasFixedSize(true)
        rvmap.adapter = Map_Item(map_Item)


        map_Item.clear()
        if(abc == 0)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "가위")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쇠사슬")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "바늘")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "전신 수영복")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "팔찌")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "운동화")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쌍안경")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "고무")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "라이터")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "마패")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "접착제")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "마늘")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "망치")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "생라면")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "꿀")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "십자가")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))

            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("골목길")

            animal1.setImageResource(R.drawable.a_wolf)
            text1.setText("늑대")
            animal2.setImageResource(R.drawable.a_bear)
            text2.setText("곰")
            animal3.setImageResource(R.drawable.a_chicken)
            text3.setText("닭")
        }

        if(abc == 1)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "단봉")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "마늘")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "대나무")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "식칼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "생라면")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "단창")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "머리띠")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "승복")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "천 갑옷")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "불경")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "마패")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "옷감")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "원석")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "종이")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "화약")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "약초")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))

            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("절")

            animal1.setImageResource(R.drawable.a_boar)
            text1.setText("멧돼지")
            animal2.setImageResource(R.drawable.a_bear)
            text2.setText("곰")
            animal3.setImageResource(R.drawable.a_bat)
            text3.setText("박쥐")
        }

        if(abc == 2)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "감시 카메라")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "옷감")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "만년필")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "머리띠")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "손목시계")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "슬리퍼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "타이즈")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "부채")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "못")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "배터리")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "오일")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "트럼프 카드")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "캔")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "꿀")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "우유")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
}
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("번화가")

            animal1.setImageResource(R.drawable.a_dog)
            text1.setText("들개")
            animal2.setImageResource(R.drawable.a_boar)
            text2.setText("멧돼지")
            animal3.setImageResource(R.drawable.a_chicken)
            text3.setText("닭")
        }
        if(abc == 3)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "단봉")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "단창")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "대나무")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "망치")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "모자")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "곡괭이")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "손도끼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "팔찌")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "꽃")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "리본")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "감시 카메라")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "올가미")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쥐덫")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "거북이 등딱지")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "원석")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "약초")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "발터 PPK")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))

            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("연못")

            animal1.setImageResource(R.drawable.a_boar)
            text1.setText("멧돼지")
            animal2.setImageResource(R.drawable.a_bear)
            text2.setText("곰")
            animal3.setImageResource(R.drawable.a_bat)
            text3.setText("박쥐")
        }
        if(abc == 4)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "목장갑")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "면도칼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "가위")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "바늘")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "붕대")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "슬리퍼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "타이즈")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "깃털")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "감시 카메라")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "고철")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "레이저 포인터")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "알코올")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "접착제")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "레몬")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "반창고")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "얼음")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "우유")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))

            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("병원")

            animal1.setImageResource(R.drawable.a_wolf)
            text1.setText("늑대")
            animal2.setImageResource(R.drawable.a_dog)
            text2.setText("들개")
            animal3.setImageResource(R.drawable.a_chicken)
            text3.setText("닭")
        }
        if(abc == 5)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "대나무")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쇠구슬")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "양궁")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "모자")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "승복")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "천 갑옷")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "운동화")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "감시 카메라")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "올가미")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "못")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "고무")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "오일")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "종이")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "화약")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "달걀")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "녹슨 검")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("양궁장")

            animal1.setImageResource(R.drawable.a_boar)
            text1.setText("멧돼지")
            animal2.setImageResource(R.drawable.a_wolf)
            text2.setText("늑대")
            animal3.setImageResource(R.drawable.a_bat)
            text3.setText("박쥐")
        }
        if(abc == 6)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "채찍")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "면도칼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "분필")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "가위")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "만년필")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "모자")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "자전거 헬멧")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "바람막이")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "붕대")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "슬리퍼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "리본")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "알코올")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "감시 카메라")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "레이저 포인터")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "라이터")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "캔")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "빵")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))

            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("학교")

            animal1.setImageResource(R.drawable.a_dog)
            text1.setText("들개")
            animal2.setImageResource(R.drawable.a_chicken)
            text2.setText("닭")
            animal3.setImageResource(R.drawable.a_bat)
            text3.setText("박쥐")
        }
        if(abc == 7)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "너클")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "대나무")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "곡괭이")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쇠사슬")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "머리띠")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "천 갑옷")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "깃털")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "꽃")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "감시 카메라")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쥐덫")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "철광석")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "화약")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "마늘")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "달걀")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "얼음")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "커피콩")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
 }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("묘지")

            animal1.setImageResource(R.drawable.a_boar)
            text1.setText("멧돼지")
            animal2.setImageResource(R.drawable.a_wolf)
            text2.setText("늑대")
            animal3.setImageResource(R.drawable.a_bat)
            text3.setText("박쥐")
        }
        if(abc == 8)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "쇠구슬")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "분필")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "석궁")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "발터 PPK")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "페도로프 자동소총")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "손도끼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "붕대")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쌍안경")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "못")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "고철")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "라이터")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "배터리")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "알코올")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "오일")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "접착제")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "카레 가루")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
 }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("공장")

            animal1.setImageResource(R.drawable.a_dog)
            text1.setText("들개")
            animal2.setImageResource(R.drawable.a_wolf)
            text2.setText("늑대")
            animal3.setImageResource(R.drawable.a_chicken)
            text3.setText("닭")
        }
        if(abc == 9)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "목장갑")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "트럼프 카드")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "페도로프 자동소총")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "식칼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "발터 PPK")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "바늘")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "바람막이")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "손목시계")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쌍안경")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "피아노선")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "고철")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "옷감")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "철광석")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "레몬")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "얼음")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "위스키")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "탄산수")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))

            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("호텔")

            animal1.setImageResource(R.drawable.a_chicken)
            text1.setText("닭")
            animal2.setImageResource(R.drawable.a_wolf)
            text2.setText("늑대")
            animal3.setImageResource(R.drawable.a_dog)
            text3.setText("들개")
        }
        if(abc == 10)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "너클")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "대나무")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쇠구슬")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "석궁")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "화승총")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "곡괭이")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "단창")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "타이즈")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "깃털")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "꽃")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "부채")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "올가미")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "원석")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "철광석")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "달걀")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "약초")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "꿀")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))

            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("숲")

            animal1.setImageResource(R.drawable.a_boar)
            text1.setText("멧돼지")
            animal2.setImageResource(R.drawable.a_wolf)
            text2.setText("늑대")
            animal3.setImageResource(R.drawable.a_bat)
            text3.setText("박쥐")
        }
        if(abc == 11)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "채직")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "면도칼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "분필")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "양궁")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "녹슨 검")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "자전거 헬멧")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "부채")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "성배")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "십자가")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "올가미")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "피아노선")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "종이")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "빵")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "위스키")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "우유")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))

            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("성당")

            animal1.setImageResource(R.drawable.a_boar)
            text1.setText("멧돼지")
            animal2.setImageResource(R.drawable.a_chicken)
            text2.setText("닭")
            animal3.setImageResource(R.drawable.a_bat)
            text3.setText("박쥐")
        }
        if(abc == 12)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "망치")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "발터 PPK")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "곡괭이")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "손도끼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쇠사슬")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "자전거 헬멧")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "전신 수영복")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쌍안경")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "감시 카메라")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "올가미")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "쥐덫")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "피아노선")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "거북이 등딱지")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "마패")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "원석")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "캔")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "탄산수")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))

            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("모래사장")

            animal1.setImageResource(R.drawable.a_boar)
            text1.setText("멧돼지")
            animal2.setImageResource(R.drawable.a_bear)
            text2.setText("곰")
            animal3.setImageResource(R.drawable.a_bat)
            text3.setText("박쥐")
        }
        if(abc == 13)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "만년필")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "바람막이")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "손목시계")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "팔찌")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "운동화")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "꽃")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "리본")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "감시 카메라")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "피아노선")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "레이저 포인터")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "오일")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "레몬")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "카레 가루")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "위스키")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "커피콩")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "탄산수")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))

            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("고급 주택가")

            animal1.setImageResource(R.drawable.a_chicken)
            text1.setText("닭")
            animal2.setImageResource(R.drawable.a_bear)
            text2.setText("곰")
            animal3.setImageResource(R.drawable.a_dog)
            text3.setText("들개")
        }
        if(abc == 14)
        {
            for(i in falselist.indices)
            {
                if(falselist[i].name1 == "단봉")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "화승총")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "녹슨 검")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "전신 수영복")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "붕대")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "감시 카메라")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "올가미")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "거북이 등딱지")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "고무")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "고철")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "라이터")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "배터리")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "생라면")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "커피콩")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "빵")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))
                if(falselist[i].name1 == "식칼")
                    map_Item.add(Map_Item.map_Itemlist(falselist[i].Image1, falselist[i].name1))

            }
            (rvmap.adapter as Map_Item).notifyDataSetChanged()
            title.setText("항구")

            animal1.setImageResource(R.drawable.a_dog)
            text1.setText("들개")
            animal2.setImageResource(R.drawable.a_bear)
            text2.setText("곰")
            animal3.setImageResource(R.drawable.a_chicken)
            text3.setText("닭")
        }
        if(abc == 15)
        {
            title.setText("연구소")

            gotcha.setText("해당 맵은 획득 아이템이 없습니다.")
            creature.setText("해당 맵은 야생동물이 존재하지 않습니다.")
            animal1.setImageResource(0)
            text1.setText("")
            animal2.setImageResource(0)
            text2.setText("")
            animal3.setImageResource(0)
            text3.setText("")
        }
    }
}